data:
  data_dir: '/home/daniel094144/SQA_code/hubert_large_5_128'
Trainer:
  n_gpu: 1,
  model_name_or_path: 'allenai/longformer-base-4096'
  max_len: 4096 
  output_dir: 'models_5_128_1e-4_warm_500_fp16'
  overwrite_output_dir: True
  per_gpu_train_batch_size: 2
  per_gpu_eval_batch_size: 2
  gradient_accumulation_steps: 16
  learning_rate: 1e-4
  evaluation_strategy: 'steps'
  max_steps: 5000
  eval_steps: 500
  save_steps: 500
  logging_steps: 20
  logging_first_step: True
  do_train: True
  warmup_steps: 500
  fp16: True
  dataloader_num_workers: 4

